### ISSUE TITLE
Setup not compatible with node 19

### ISSUE THREAD

**Issue by koliyo** [tanainc/tana-import-tools#16]
The `--es-module-specifier-resolution=node` setup does not work in node 19

https://stackoverflow.com/questions/62619058/appending-js-extension-on-relative-import-statements-during-typescript-compilat#comment133508037_70774908

SO comment suggests using this loader: https://github.com/barhun/extensionless

**Comment by shawnyeager** [comment]
Further, `yarn install` fails with any version of node > 18. Current node release is 21.5.0.
