### ISSUE TITLE
Add Logseq to import tools

### ISSUE THREAD

**Issue by davidjaggi** [tanainc/tana-import-tools#2]
As a frequent Logseq user, I have all of my notes stored in Logseq. A good import solution into Tana will be vital to make the switch as smooth as possible.

**Comment by houshuang** [comment]
If you look at the first pull request, it already adds rudimentary support for importing Logseq. The goal of making this repository open source is to enable the user community to build out support for the tools that they want. Feel free to test the code in PR #1 and submit PRs to improve it, or specific feature requests/bug reports to the author, etc.

**Comment by jkmaxwell** [comment]
@houshuang fully understood. i think one of the dilemmas users face is not wanting to pollute their KB. early access != beta testers.

**Comment by jkmaxwell** [comment]
like this isn't reasonable for any casual user expecting the content to import:

![image](https://user-images.githubusercontent.com/342903/195654593-fdc027e5-be1b-4ed3-b6d4-eb828faebd32.png)

i'm not complaining "someone should have done better!!!" i'm just saying this isn't yet a tool people can use to migrate from logseq to tana. not everyone is an engineer and can just dive in to scratch their own itches. @davidjaggi's request remains valid and eventually enough engineers who care about this can make it a reality.

**Comment by jkmaxwell** [comment]
@houshuang having thought about this for a few hours I'll offer a different lens in the form of a question:

Can you please advise how a user could test importing their Logseq data, to help you test, in a quarantined KB that does not pollute their primary?

Thank you!

**Comment by houshuang** [comment]
@jkmaxwell Well every single import happens in a separate workspace, which you can remove afterwards, so that should not be a problem. Feel free to look at the Roam import video in the help center for how this looks. It would be the same with Logseq or Obsidian data.

**Comment by houshuang** [comment]
I appreciate your interest and enthusiasm. I totally agree that the list above is not reasonable for any casual user, and Tana has never said that we offer well supported Logseq support. We'd love to support lot's of products' data, but we don't have the capacity to support anything other than Roam yet, so we made this open source collaboration. Once Obsidian and Logseq are mature enough, we'll include them directly in the Tana interface and support them with help center docs etc, then they will be ready for casual users. Currently it's only for people very happy with experimentation.
